# Generated by Django 5.1.4 on 2025-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userhasroles',
            constraint=models.UniqueConstraint(fields=('id_user', 'id_rol'), name='unique_user_role'),
        ),
    ]
