# Generated by Django 5.1.4 on 2025-03-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userhasroles_unique_user_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userhasroles',
            name='unique_user_role',
        ),
    ]
